=== CRTandKDU/NCloseCompiler/kbml.dtd
<?xml encoding="ISO-8859-1"?>

<!-- @version:  2010.06.26 -->

<!-- `ruleset' groups related rules -->
<!ELEMENT ruleset (rule)+>
<!ATTLIST ruleset name CDATA #IMPLIED>

<!-- `rule' builds a single NClose cond->hypo, and optional actions, rule -->
<!ELEMENT rule (hypothesis,condition,action?)>
<!ATTLIST rule name CDATA #IMPLIED>


<!ELEMENT var (#PCDATA)>
<!ELEMENT const (#PCDATA)>
<!ELEMENT test (const|var)+>
<!ATTLIST test op CDATA #REQUIRED>
<!ELEMENT condition (test)+>
<!ELEMENT hypothesis (#PCDATA)>

<!ELEMENT action (command)+>
<!ELEMENT command (var|const)+>
<!ATTLIST command op CDATA #REQUIRED>

=== CRTandKDU/NCloseCompiler/test1.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE ruleset SYSTEM "kbml.dtd">

<!-- @version: -->

<ruleset name="String-types tests">
  <rule>
    <hypothesis>InTheMiddle</hypothesis>
    <condition>
      <test op="in"><var>user</var>
	<const>reese</const>
	<const>malcolm</const>
	<var>person</var>
	<const>dewey</const>
	<const>francis</const>
      </test>
      <test op="gt"><var>y</var><const>4.5</const></test>
    </condition>
    <action>
      <command op="set-num">
	<var>x</var>
	<const>221.65</const>
      </command>
      <command op="set-bool">
	<var>b1</var>
	<const>true</const>
      </command>
      <command op="set-bool">
	<var>b2</var>
	<const>false</const>
      </command>
    </action>
  </rule>
  <rule>
    <hypothesis>Diff</hypothesis>
    <condition>
      <test op="in"><var>user</var><const>joe</const></test>
    </condition>
  </rule>
</ruleset>

=== CRTandKDU/NCloseCompiler/test.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE ruleset SYSTEM "kbml.dtd">

<!-- @version: -->

<ruleset name="Test KB from test.xml">
  <rule>
    <hypothesis>H007</hypothesis>
    <condition>
      <test op="yes"><var>bool1</var></test>
    </condition>
  </rule>
  <rule>
    <hypothesis>H2</hypothesis>
    <condition>
      <test op="gt"><var>bool2</var><var>bool31</var></test>
      <test op="lt"><var>bool2</var><const>103.56</const></test>
      <test op="gt"><var>bool32</var><const>3.56</const></test>
      <test op="yes"><var>bool22</var></test>
    </condition>
    <action>
      <command op="set-num">
	<var>x1</var>
	<const>221.65</const>
      </command>
      <command op="set-bool">
	<var>newb1</var>
	<const>true</const>
      </command>
    </action>
  </rule>
  <rule>
    <hypothesis>H2Diff</hypothesis>
    <condition>
      <test op="lt"><var>bool2</var><const>7.0</const></test>
    </condition>
    <action>
      <command op="set-num">
	<var>x2</var>
	<const>221.65</const>
      </command>
      <command op="set-bool">
	<var>b3</var>
	<const>true</const>
      </command>
      <command op="set-bool">
	<var>b4</var>
	<const>false</const>
      </command>
    </action>
  </rule>
  <rule>
    <hypothesis>H2</hypothesis>
    <condition>
      <test op="yes"><var>bool23</var></test>
      <test op="lt"><var>bool2</var><const>0.0</const></test>
    </condition>
  </rule>
  <rule>
    <hypothesis>H1</hypothesis>
    <condition>
      <test op="no"><var>bool3</var></test>
    </condition>
  </rule>
  <rule>
    <hypothesis>H1</hypothesis>
    <condition>
      <test op="yes"><var>bool4</var></test>
      <test op="yes"><var>H6</var></test>
      <test op="no"><var>bool5</var></test>
      <test op="no"><var>H6</var></test>
    </condition>
  </rule>
  <rule>
    <hypothesis>H6</hypothesis>
    <condition>
      <test op="yes"><var>bool14</var></test>
      <test op="no"><var>bool15</var></test>
    </condition>
  </rule>
</ruleset>
